name: Build and Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

jobs:
  validate:
    name: Install, Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Cache node modules for faster builds
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting to check code quality
      - name: Run Lint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm test

      # Build the project
      - name: Build the project
        run: npm run build

      # Upload build artifacts for review
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build/

  notify:
    name: Notify on Build Status
    runs-on: ubuntu-latest
    needs: validate
    steps:
      # Example for Slack Notification
      - name: Send Notification to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          slack-message: "Build Status: ${{ job.status }}"
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
